on:
  pull_request:

  push:
    branches:
      - "main"

  workflow_dispatch: {}

name: Build

jobs:
  build:
    name: "build"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # x86_64 linux
          - os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true

      - name: build go runner
        run: go build -o runner ./cmd

      - name: run interpreted, with extra memory
        run: ./runner -release -interp
      - name: run compiled, without extra memory
        run: ./runner -release -nomem
      - name: run compiled, with extra memory (crashes)
        run: ./runner -release
